# Generated by Django 5.1 on 2024-08-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_tweet_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='photos/'),
        ),
    ]
